<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>JobHunter.Api</AssemblyName>
    <RootNamespace>JobHunter.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobHunter.Application\JobHunter.Application.csproj" />
    <ProjectReference Include="..\JobHunter.Infrastructure\JobHunter.Infrastructure.csproj" />
  </ItemGroup>

</Project>
